#!/usr/bin/env python3
"""
ex03_workflow

Demonstrates the high-level view_factor_outside_workflow:
- Computes the regular scene view-factor matrix
- Computes Radiance-style Tregenza sky view factors (merged by default)
- Returns the residual necessary so that ``scene + sky + rest == 1`` for each
  emitter without redistributing energy to specific geometry.

Outputs:
- Saves geometry, parameters, scene, sky and residual VFs to
  vf_workflow.raystrack/
- Prints the residual remainder per emitter

Configuration overview:
- Source geometry: expects `street_canyon.json` generated by ex00.
- `matrix_params`: controls the scene matrix pass (use `MatrixParams`). Key fields include `samples`,
  `rays`, `seed`, `bvh`, `device`, `tol`, `tol_mode`, `max_iters`, and
  `min_iters`. With `reciprocity=False` and `enforce_reciprocity_rowsum=False`,
  the solver leaves "rest" energy instead of distributing it back onto surfaces.
- `sky_params`: mirrors the sampling configuration for the sky pass (use `SkyParams`); `tol_mode`
  stays on `"stderr"` to keep statistical error checks comparable.
- The sky pass always returns a single merged `"Sky"` receiver.
- The workflow returns `vf_scene`, `sky_vf`, and `rest_vf`, which are persisted
  together with the inputs via `save_run` for further analysis.
"""
import sys
from pathlib import Path


def ensure_repo_on_path():
    here = Path(__file__).resolve().parent
    repo_root = here.parent
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))


def main():
    ensure_repo_on_path()
    from raystrack.io import load_meshes_json
    from raystrack import save_run, view_factor_outside_workflow
    from raystrack.params import MatrixParams, SkyParams

    here = Path(__file__).resolve().parent
    geom = here / "street_canyon.json"
    if not geom.exists():
        raise FileNotFoundError(
            f"Geometry not found at {geom}. Run ex00_street_canyon_geometry.py first.")

    meshes = load_meshes_json(str(geom))

    # Balanced preview settings for this 22-triangle scene. Increase the ray
    # budget or tighten tol when validating smaller differences between VFs.
    matrix_params = MatrixParams(
        samples=16,
        rays=128,
        seed=7,
        bvh="auto",
        device="auto",
        cuda_async=True,
        gpu_raygen=True,
        max_iters=100,
        tol=1e-4,
        tol_mode="stderr",  # matrix algorithm supports 'delta' and 'stderr'
        min_iters=5,
        enforce_reciprocity_rowsum=False, # True means that all surfaces get extra weighted vf to match rowsum = 1; False means there is a rest
        reciprocity=True,
    )
    sky_params = SkyParams(
        samples=16,
        rays=128,
        seed=7,
        bvh="auto",
        device="auto",
        cuda_async=True,
        gpu_raygen=True,
        max_iters=100,
        tol=1e-4,          # stderr target for merged sky
        tol_mode="stderr", # use true stderr convergence for sky
        min_iters=5,
        discrete=False,
    )

    # Use merged sky output
    vf_scene, sky_vf, rest_vf = view_factor_outside_workflow(
        meshes,
        matrix_params=matrix_params,
        sky_params=sky_params,
    )

    # Print a short reconciliation summary
    print("Emitter                            sum(scene)        Sky          Rest        Total")
    print("-" * 96)
    for name, row in vf_scene.items():
        scene_sum = float(sum(float(v) for v in row.values()))
        sky_total = float(sky_vf.get(name, {}).get("Sky", 0.0))
        resid = float(rest_vf.get(name, {}).get("Rest", 0.0))
        total = scene_sum + sky_total + resid
        print(f"{name:32s}  {scene_sum:>10.6f}   {sky_total:>10.6f}    {resid:+.6e}   {total:>10.6f}")

    # Use a fresh output path; save_run protects an existing run from overwrite.
    out = here / "vf_workflow.raystrack"
    suffix = 1
    while out.exists():
        out = here / f"vf_workflow_{suffix:03d}.raystrack"
        suffix += 1
    saved = save_run(
        out,
        meshes=meshes,
        matrix_params=matrix_params,
        sky_params=sky_params,
        scene=vf_scene,
        sky=sky_vf,
        rest=rest_vf,
    )
    print(f"Saved complete run to: {saved}")


if __name__ == "__main__":
    main()
    from raystrack.utils.helpers import hold_console_open
    hold_console_open()

